# Largely based on the official Astro action
# https://docs.astro.build/en/guides/deploy/github/
name: Deploy to Netlify Staging

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches:
      - '**'

  # Trigger workflow when PR is opened or updated  
  pull_request:
    types: [opened, edited]
    
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'Build and Deploy to Staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Install Netlify 
        run: npm install -g netlify-cli

      # Used to checkout the current branch at HEAD from this repo
      - uses: actions/checkout@v3

      # Runs the netlify deploy commands
      - uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Test deploy v${{ github.ref }}"
          build_directory: "./dist"
          debug: ${{ vars.DEBUG_BUILD }}
          build_command: netlify build
          install_command: npm install

      - name: Comment on PR with deploy URL
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The site has been deployed! You can preview it here: ${{ steps.deploy.outputs.NETLIFY_PREVIEW_URL }}
      

