# Largely based on the official Astro action
# https://docs.astro.build/en/guides/deploy/github/
name: Deploy to Netlify Staging

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    environment: netlify-wills-org

    steps:
      - name: Install Netlify 
        run: npm install -g netlify-cli

      # Used to checkout the current branch at HEAD from this repo
      - uses: actions/checkout@v3

      # Runs the netlify deploy commands
      - uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Test deploy v${{ github.ref }}"
          deploy_alias: ${{ env.BRANCH_NAME }}
          build_directory: "./dist"
          build_commpand: netlify build
          install_command: npm install
      

